'use client';

import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import AppShell from '../../../../components/AppShell';
import LoadingState from '../../../../components/LoadingState';
import StatusBadge from '../../../../components/StatusBadge';
import { api, type AuditEvent } from '../../../../../lib/api';

export default function ConnectionAuditPage() { const { targetId } = useParams<{ targetId: string }>(); const [events, setEvents] = useState<AuditEvent[]>(); const [message, setMessage] = useState(''); useEffect(() => { api<{ items: AuditEvent[] }>(`/targets/${targetId}/connection/audit`).then((r) => setEvents(r.items)).catch((e) => setMessage(e instanceof Error ? e.message : 'CONNECTION_AUDIT_FAILED')); }, [targetId]); return <AppShell breadcrumb={`Tenant / Database / ${targetId} / Connection audit`}><div className="page-heading"><div><p className="eyebrow">DATABASE · AUDIT</p><h1>Connection Audit Panel</h1><p className="muted">Detailed log of connection attempts and configuration changes.</p></div><button className="button secondary" type="button">⇩ Export CSV</button></div>{message ? <div className="alert danger-box">{message}</div> : null}{!events && !message ? <LoadingState /> : null}<section className="panel table-panel connection-audit"><table><thead><tr><th>Timestamp</th><th>Actor</th><th>Action</th><th>Target</th><th>Secret ref</th><th>Result</th><th>Correlation</th></tr></thead><tbody>{events?.map((event) => <tr key={event.id}><td className="code small">{new Date(event.createdAt).toISOString()}</td><td className="code">{event.actorId}</td><td><span className="event-tag">{event.action}</span></td><td className="code">{event.resourceId.slice(0, 8)}…</td><td className="code">{typeof event.metadata.secretRef === 'string' ? event.metadata.secretRef : '—'}</td><td><StatusBadge status={typeof event.metadata.status === 'string' ? event.metadata.status : 'RECORDED'} /></td><td className="code">{typeof event.metadata.correlationId === 'string' ? event.metadata.correlationId : '—'}</td></tr>)}</tbody></table>{!events?.length && events ? <div className="empty-state"><p>No connection events yet.</p></div> : null}</section></AppShell>; }
