'use client';

import { useState, type FormEvent } from 'react';
import AppShell from '../components/AppShell';
import { api } from '../../lib/api';

export default function ManualMigrationPage() {
  const [message, setMessage] = useState(''); const [submitting, setSubmitting] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitting(true); setMessage(''); const form=new FormData(event.currentTarget); const targetId=String(form.get('targetId')??''); try { const result=await api<{id:string}>(`/targets/${targetId}/manual-migrations`,{method:'POST',body:JSON.stringify({sqlPayload:String(form.get('sqlPayload')??''),versionContext:String(form.get('versionContext')??'')||undefined,executionSequence:form.get('executionSequence')?Number(form.get('executionSequence')):undefined,reason:String(form.get('reason')??''),outOfOrder:Boolean(form.get('executionSequence'))})}); setMessage(`Draft ${result.id} created. It is not executed until it enters an approved plan.`); event.currentTarget.reset(); } catch(e) { setMessage(e instanceof Error?e.message:'MANUAL_MIGRATION_FAILED'); } finally { setSubmitting(false); } }
  return <AppShell breadcrumb="Tenant / Manual SQL"><div className="page-heading"><div><p className="eyebrow">MANUAL_UI · EXCEPTION PATH</p><h1>Register manual SQL</h1><p className="muted">Manual SQL remains in the control plane and is never synced back to Git.</p></div></div><form className="panel form" onSubmit={submit}><div className="form-grid"><label>Target ID<input name="targetId" required placeholder="UUID of configured target" /></label><label>Version context<input name="versionContext" placeholder="V7 or repair-2026-08" /></label></div><label>SQL payload<textarea name="sqlPayload" required rows={15} placeholder="CREATE INDEX ..." /></label><div className="form-grid"><label>Execution sequence<input name="executionSequence" type="number" min={1} placeholder="Optional" /></label><label>Reason<input name="reason" required placeholder="Why is this outside Git?" /></label></div><div className="warning-box">High impact: this creates an auditable draft. Backup, preflight and approval are required before target execution.</div><button className="button primary" disabled={submitting}>{submitting?'Saving draft…':'Create migration draft'}</button>{message?<p className="small muted" role="status">{message}</p>:null}</form></AppShell>;
}
