'use client';

import { useEffect, useState, type FormEvent } from 'react';
import AppShell from '../components/AppShell';
import { api, type Target } from '../../lib/api';

export default function ManualMigrationPage() {
  const [targets, setTargets] = useState<Target[]>(); const [message, setMessage] = useState(''); const [submitting, setSubmitting] = useState(false);
  useEffect(() => { api<{ items: Target[] }>('/targets').then((response) => setTargets(response.items)).catch((error) => setMessage(error instanceof Error ? error.message : 'TARGETS_FAILED')); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setSubmitting(true); setMessage(''); const form = new FormData(event.currentTarget); const targetId = String(form.get('targetId') ?? ''); try { const draft = await api<{ id: string }>(`/targets/${targetId}/manual-migrations`, { method: 'POST', body: JSON.stringify({ sqlPayload: String(form.get('sqlPayload') ?? ''), versionContext: String(form.get('versionContext') ?? '') || undefined, executionSequence: form.get('executionSequence') ? Number(form.get('executionSequence')) : undefined, reason: String(form.get('reason') ?? ''), outOfOrder: Boolean(form.get('executionSequence')) }) }); const plan = await api<{ id: string }>(`/manual-migrations/${draft.id}/plan`, { method: 'POST', body: '{}' }); window.location.assign(`/plans/${plan.id}`); } catch (error) { setMessage(error instanceof Error ? error.message : 'MANUAL_MIGRATION_FAILED'); } finally { setSubmitting(false); } }
  return <AppShell breadcrumb="Tenant / Manual SQL"><div className="page-heading"><div><p className="eyebrow">MANUAL_UI · EXCEPTION PATH</p><h1>Register manual SQL</h1><p className="muted">Manual SQL remains in the control plane and is never synced back to Git.</p></div></div><form className="panel form" onSubmit={submit}><div className="form-grid"><label>Target<select name="targetId" required defaultValue=""><option value="" disabled>Select target</option>{targets?.map((target) => <option value={target.id} key={target.id}>{target.name} · {target.databaseName}.{target.schemaName}</option>)}</select><span className="small muted">Target must be configured before manual SQL can be drafted.</span></label><label>Version context<input name="versionContext" placeholder="V7 or repair-2026-08" /></label></div><label>SQL payload<textarea name="sqlPayload" required rows={15} placeholder="CREATE INDEX ..." /></label><div className="form-grid"><label>Execution sequence<input name="executionSequence" type="number" min={1} placeholder="Optional" /></label><label>Reason<input name="reason" required placeholder="Why is this outside Git?" /></label></div><div className="warning-box">High impact: this creates a draft and opens a plan. Backup, preflight and approval remain required before execution.</div><button className="button primary" disabled={submitting || !targets?.length}>{submitting ? 'Creating plan…' : 'Create migration plan'}</button>{message ? <p className="small muted" role="status">{message}</p> : null}</form></AppShell>;
}
