'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import AppShell from '../../components/AppShell';
import LoadingState from '../../components/LoadingState';
import { api, type Project, type Target } from '../../../lib/api';

export default function ProjectDetailPage() { const {projectId}=useParams<{projectId:string}>(); const [project,setProject]=useState<Project>(); const [targets,setTargets]=useState<Target[]>([]); const [message,setMessage]=useState(''); useEffect(()=>{if(!projectId)return; Promise.all([api<{items:Project[]}>('/projects'),api<{items:Target[]}>(`/targets?projectId=${projectId}`)]).then(([p,t])=>{setProject(p.items.find((item)=>item.id===projectId));setTargets(t.items);}).catch((e)=>setMessage(e instanceof Error?e.message:'PROJECT_FAILED'));},[projectId]); async function sync(){setMessage('Syncing Git source…');try{await api(`/projects/${projectId}/sync`,{method:'POST',body:'{}'});setMessage('Source snapshot synced. Refresh inventory to inspect parsed files.');}catch(e){setMessage(e instanceof Error?e.message:'GIT_SYNC_FAILED');}} return <AppShell breadcrumb={`Tenant / Project / ${project?.name??projectId}`}><div className="page-heading"><div><p className="eyebrow">PROJECT CONTROL</p><h1>{project?.name??'Project'}</h1><p className="muted">{project?.repositoryUrl??'Loading repository metadata…'}</p></div><button className="button primary" type="button" onClick={sync}>Sync Git source</button></div>{!project&&!message?<LoadingState/>:null}{message?<p className="small muted" role="status">{message}</p>:null}{project?<><section className="detail-grid"><article className="panel"><p className="label-caps">SOURCE</p><h2>Repository connection</h2><dl className="definition-list"><dt>Repository</dt><dd className="code">{project.repositoryUrl}</dd><dt>Default ref</dt><dd className="code">{project.defaultRef}</dd><dt>Migration path</dt><dd className="code">{project.migrationPath}</dd><dt>Database engine</dt><dd>{project.databaseEngine}</dd></dl></article><article className="panel"><p className="label-caps">TARGETS</p><h2>Environment mappings</h2>{targets.length?targets.map((target)=><Link className="list-card" href={`/targets/${target.id}`} key={target.id}><strong>{target.name}</strong><span className="small muted">{target.databaseName} · {target.schemaName} · {target.gitRef}</span></Link>):<div className="empty-state"><p>No targets mapped.</p><span className="small muted">Target creation is guarded by tenant admin permission.</span></div>}</article></section></>:null}</AppShell>; }
