import cors from '@fastify/cors';
import Fastify, { type FastifyInstance } from 'fastify';
import { createRemoteJWKSet, jwtVerify, type JWTPayload } from 'jose';
import { randomUUID } from 'node:crypto';
import { z } from 'zod';
import { checksumSql, databaseEngines, type Actor, type DatabaseEngine, type SecretBackend, type SslMode } from './domain.js';
import { syncProjectSource } from './git-source.js';
import { actorFromClaims, AuthorizationError, requirePermission } from './rbac.js';
import { buildPlan } from './planner.js';
import { executeOperation } from './operation-runner.js';
import { backendSupportsCredentialWrite, connectionSecretFor, KubernetesConnectionSecretStore, testConnection, type ConnectionSecretStore } from './secret-store.js';
import { evaluatePreflight } from './preflight.js';
import type { Store } from './store.js';

declare module 'fastify' {
  interface FastifyRequest { actor?: Actor; claims?: JWTPayload; }
}

const uuid = z.string().uuid();
const tenantSchema = z.object({ name: z.string().trim().min(1).max(120), slug: z.string().trim().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(80) });
const projectSchema = z.object({ tenantId: uuid, name: z.string().trim().min(1).max(120), databaseEngine: z.enum(databaseEngines), repositoryUrl: z.string().url(), defaultRef: z.string().trim().min(1).max(200).default('master'), migrationPath: z.string().trim().min(1).max(300).default('migrations') });
const environmentSchema = z.object({ projectId: uuid, name: z.string().trim().min(1).max(80) });
const targetSchema = z.object({ projectId: uuid, environmentId: uuid, name: z.string().trim().min(1).max(120), gitRef: z.string().trim().min(1).max(200).default('master'), databaseName: z.string().trim().min(1).max(200), schemaName: z.string().trim().min(1).max(200), secretRef: z.string().trim().min(1).max(300) });
const manualMigrationSchema = z.object({ sqlPayload: z.string().trim().min(1).max(1_000_000), versionContext: z.string().max(120).optional(), executionLabel: z.string().max(200).optional(), executionSequence: z.number().int().positive().optional(), outOfOrder: z.boolean().default(false), reason: z.string().max(1_000).optional() });
const planSchema = z.object({ fromVersion: z.string().max(120).optional(), toVersion: z.string().max(120).optional(), autoApprove: z.boolean().default(false) });
const approvalSchema = z.object({ decision: z.enum(['APPROVED', 'REJECTED']), reason: z.string().max(1_000).optional() });
const backupPlanSchema = z.object({ scriptRef: z.string().trim().min(1).max(500), requiredBeforeExecute: z.boolean().default(true), retentionDays: z.number().int().min(1).max(3650).default(30) });
const backupArtifactSchema = z.object({ artifactRef: z.string().trim().min(1).max(500), checksum: z.string().trim().max(200).optional(), scopeFromVersion: z.string().max(120).optional(), scopeToVersion: z.string().max(120).optional(), expiresAt: z.string().datetime().optional() });
const nativeHistorySchema = z.object({ engine: z.enum(databaseEngines), tableName: z.string().trim().min(1).max(300), installedRank: z.number().int().optional(), version: z.string().max(200).optional(), description: z.string().max(500).optional(), checksum: z.string().max(200).optional(), success: z.boolean(), installedAt: z.string().datetime().optional(), evidence: z.record(z.unknown()).default({}) });
const connectionSchema = z.object({ host: z.string().trim().min(1).max(255), port: z.number().int().min(1).max(65535), databaseName: z.string().trim().min(1).max(200), schemaName: z.string().trim().min(1).max(200), username: z.string().trim().min(1).max(200), password: z.string().min(1).max(1000).optional(), secretBackend: z.enum(['kubernetes', 'vault', 'external-secrets']).default('kubernetes'), secretRef: z.string().trim().min(1).max(253).optional(), sslMode: z.enum(['disable', 'require', 'verify-ca', 'verify-full']).default('require'), timeoutSeconds: z.number().int().min(1).max(300).default(30) });
const rotateCredentialSchema = z.object({ password: z.string().min(1).max(1000), reason: z.string().trim().min(1).max(1000), confirm: z.literal(true) });

export type BuildAppOptions = { secretManager?: ConnectionSecretStore; connectionTester?: typeof testConnection };

function actorFor(request: { actor?: Actor; headers: Record<string, string | string[] | undefined> }): Actor {
  if (request.actor) return request.actor;
  const configured = request.headers['x-actor-id'];
  return { id: typeof configured === 'string' && configured.trim() ? configured.trim() : 'local-development', roles: ['TENANT_ADMIN'] };
}
function params(request: { params: unknown }): Record<string, string | undefined> { return request.params as Record<string, string | undefined>; }
function sendValidation(reply: { code: (status: number) => { send: (body: unknown) => unknown } }, parsed: { success: boolean; error?: unknown }) { return reply.code(400).send({ code: 'VALIDATION_ERROR', details: parsed.success ? undefined : parsed.error }); }

async function assertTenantScope(store: Store, actor: Actor, tenantId: string): Promise<void> {
  if (actor.tenantIds?.length && !actor.tenantIds.includes(tenantId)) throw new AuthorizationError('The actor is outside the tenant scope');
  if (!(await store.listTenants()).some((tenant) => tenant.id === tenantId)) throw new AuthorizationError('Tenant scope is not valid');
}
async function assertProjectScope(store: Store, actor: Actor, projectId: string): Promise<void> {
  const project = await store.getProject(projectId);
  if (!project) throw new AuthorizationError('Project scope is not valid');
  await assertTenantScope(store, actor, project.tenantId);
}
async function assertTargetScope(store: Store, actor: Actor, targetId: string): Promise<void> {
  const target = await store.getTarget(targetId);
  if (!target) throw new AuthorizationError('Target scope is not valid');
  await assertProjectScope(store, actor, target.projectId);
}

export async function buildApp(store: Store, options: BuildAppOptions = {}): Promise<FastifyInstance> {
  const app = Fastify({ logger: { level: process.env.LOG_LEVEL ?? 'info' } });
  const corsOrigins = process.env.CORS_ORIGINS?.split(',').map((origin) => origin.trim()).filter(Boolean);
  await app.register(cors, { origin: process.env.NODE_ENV === 'production' ? (corsOrigins ?? false) : true });
  const authMode = process.env.AUTH_MODE ?? (process.env.NODE_ENV === 'production' ? 'oidc' : 'mock');
  let jwks: ReturnType<typeof createRemoteJWKSet> | undefined;
  if (authMode === 'oidc') { const jwksUrl = process.env.OIDC_JWKS_URL; if (!jwksUrl) throw new Error('OIDC_JWKS_URL is required when AUTH_MODE=oidc'); jwks = createRemoteJWKSet(new URL(jwksUrl)); }
  const secretManager = options.secretManager ?? (process.env.KUBERNETES_SERVICE_HOST ? new KubernetesConnectionSecretStore() : undefined);
  const connectionTester = options.connectionTester ?? testConnection;

  app.addHook('preHandler', async (request, reply) => {
    if (!request.url.startsWith('/api/v1') || authMode === 'mock') return;
    if (!jwks) return reply.code(503).send({ code: 'AUTH_NOT_CONFIGURED' });
    const authorization = request.headers.authorization;
    if (!authorization?.startsWith('Bearer ')) return reply.code(401).send({ code: 'UNAUTHENTICATED' });
    try {
      const verified = await jwtVerify(authorization.slice('Bearer '.length), jwks, { issuer: process.env.OIDC_ISSUER, audience: process.env.OIDC_AUDIENCE });
      request.claims = verified.payload;
      request.actor = actorFromClaims(verified.payload.sub ?? 'unknown-subject', verified.payload as Record<string, unknown>);
      const path = request.url.split('?')[0];
      const targetMatch = path.match(/^\/api\/v1\/targets\/([^/]+)/);
      const projectMatch = path.match(/^\/api\/v1\/projects\/([^/]+)/);
      if (targetMatch) await assertTargetScope(store, request.actor, targetMatch[1]);
      else if (projectMatch) await assertProjectScope(store, request.actor, projectMatch[1]);
    } catch (error) { if (error instanceof AuthorizationError) throw error; request.log.warn({ err: error }, 'OIDC token verification failed'); return reply.code(401).send({ code: 'INVALID_TOKEN' }); }
  });

  app.setErrorHandler((error, request, reply) => {
    if (error instanceof AuthorizationError) return reply.code(403).send({ code: error.code, message: error.message });
    request.log.error({ err: error }, 'request failed');
    return reply.code(500).send({ code: 'INTERNAL_ERROR', correlationId: request.id });
  });
  app.get('/health', async () => ({ status: 'ok', service: 'schemaops-backend' }));
  app.get('/ready', async (_request, reply) => { try { await store.ready(); return { status: 'ready' }; } catch (error) { app.log.error({ err: error }, 'control-plane database is not ready'); return reply.code(503).send({ status: 'not_ready' }); } });

  app.get('/api/v1/dashboard', async (request) => {
    const actor = actorFor(request); requirePermission(actor, 'target:view');
    const [allProjects, allTargets, allOperations, allAudit] = await Promise.all([store.listProjects(), store.listTargets(), store.listOperations(), store.listAuditEvents(undefined, 100)]);
    const projects = actor.tenantIds?.length ? allProjects.filter((project) => actor.tenantIds?.includes(project.tenantId)) : allProjects;
    const projectIds = new Set(projects.map((project) => project.id));
    const targets = allTargets.filter((target) => projectIds.has(target.projectId));
    const targetIds = new Set(targets.map((target) => target.id));
    const operations = allOperations.filter((operation) => targetIds.has(operation.targetId));
    const audit = actor.tenantIds?.length ? allAudit.filter((event) => event.tenantId && actor.tenantIds?.includes(event.tenantId)) : allAudit.slice(0, 10);
    return { metrics: { projects: projects.length, targets: targets.length, pendingMigrations: 0, failedRuns: operations.filter((o) => o.status === 'FAILED').length }, projects, targets, operations: operations.slice(0, 10), audit: audit.slice(0, 10) };
  });

  app.get('/api/v1/tenants', async (request) => { const actor=actorFor(request); requirePermission(actor, 'target:view'); const tenants=await store.listTenants(); return { items: actor.tenantIds?.length ? tenants.filter((tenant) => actor.tenantIds?.includes(tenant.id)) : tenants }; });
  app.post('/api/v1/tenants', async (request, reply) => { const actor=actorFor(request); requirePermission(actor,'access:admin'); const parsed=tenantSchema.safeParse(request.body); if(!parsed.success) return sendValidation(reply,parsed); return reply.code(201).send(await store.createTenant(parsed.data)); });
  app.get('/api/v1/projects', async (request) => { const actor=actorFor(request); requirePermission(actor, 'target:view'); const projects=await store.listProjects(); return { items: actor.tenantIds?.length ? projects.filter((project) => actor.tenantIds?.includes(project.tenantId)) : projects }; });
  app.post('/api/v1/projects', async (request, reply) => { const actor=actorFor(request); requirePermission(actor, 'access:admin'); const parsed=projectSchema.safeParse(request.body); if(!parsed.success) return sendValidation(reply,parsed); await assertTenantScope(store,actor,parsed.data.tenantId); return reply.code(201).send(await store.createProject(parsed.data)); });
  app.get('/api/v1/projects/:projectId/environments', async (request, reply) => { const projectId=uuid.safeParse(params(request).projectId); if(!projectId.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); const actor=actorFor(request); requirePermission(actor,'target:view'); await assertProjectScope(store,actor,projectId.data); return {items:await store.listEnvironments(projectId.data)}; });
  app.post('/api/v1/environments', async (request, reply) => { const actor=actorFor(request); requirePermission(actor,'access:admin'); const parsed=environmentSchema.safeParse(request.body); if(!parsed.success) return sendValidation(reply,parsed); await assertProjectScope(store,actor,parsed.data.projectId); return reply.code(201).send(await store.createEnvironment(parsed.data)); });

  app.get('/api/v1/targets', async (request) => { const actor=actorFor(request); requirePermission(actor, 'target:view'); const projectId=typeof (request.query as {projectId?:unknown})?.projectId==='string' ? (request.query as {projectId:string}).projectId : undefined; if(projectId) await assertProjectScope(store,actor,projectId); const targets=await store.listTargets(projectId); if(!actor.tenantIds?.length) return {items:targets}; const projects=await store.listProjects(); const allowed=new Set(projects.filter((project) => actor.tenantIds?.includes(project.tenantId)).map((project) => project.id)); return {items:targets.filter((target) => allowed.has(target.projectId))}; });
  app.post('/api/v1/targets', async (request, reply) => { const actor=actorFor(request); requirePermission(actor,'access:admin'); const parsed=targetSchema.safeParse(request.body); if(!parsed.success) return sendValidation(reply,parsed); await assertProjectScope(store,actor,parsed.data.projectId); if(!(await store.listEnvironments(parsed.data.projectId)).some((environment) => environment.id === parsed.data.environmentId)) return reply.code(400).send({code:'ENVIRONMENT_PROJECT_MISMATCH'}); return reply.code(201).send(await store.createTarget(parsed.data)); });
  app.post('/api/v1/projects/:projectId/sync', async (request, reply) => { const actor=actorFor(request); requirePermission(actor,'target:sync'); const projectId=uuid.safeParse(params(request).projectId); if(!projectId.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); await assertProjectScope(store,actor,projectId.data); const body=z.object({gitRef:z.string().trim().min(1).max(200).optional()}).safeParse(request.body ?? {}); if(!body.success) return sendValidation(reply,body); const snapshot=await syncProjectSource(store,projectId.data,body.data.gitRef,actor.id); return reply.code(snapshot.status==='SUCCEEDED'?201:422).send(snapshot); });

  app.get('/api/v1/targets/:targetId/inventory', async (request, reply) => { const targetId=uuid.safeParse(params(request).targetId); if(!targetId.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); requirePermission(actorFor(request),'target:view'); const target=await store.getTarget(targetId.data); if(!target) return reply.code(404).send({code:'TARGET_NOT_FOUND'}); return {items:await store.listInventory(target.id)}; });
  app.get('/api/v1/targets/:targetId/connection', async (request, reply) => { const targetId=uuid.safeParse(params(request).targetId); if(!targetId.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); requirePermission(actorFor(request),'target:view'); const connection=await store.getTargetConnection(targetId.data); if(!connection) return reply.code(404).send({code:'TARGET_NOT_FOUND'}); return connection; });
  app.put('/api/v1/targets/:targetId/connection', async (request, reply) => {
    const actor=actorFor(request); requirePermission(actor,'access:admin'); const targetId=uuid.safeParse(params(request).targetId); const parsed=connectionSchema.safeParse(request.body); if(!targetId.success||!parsed.success) return reply.code(400).send({code:'VALIDATION_ERROR',details:parsed.success?'invalid targetId':parsed.error.flatten()}); const target=await store.getTarget(targetId.data); if(!target) return reply.code(404).send({code:'TARGET_NOT_FOUND'}); const project=await store.getProject(target.projectId); if(!project) return reply.code(404).send({code:'PROJECT_NOT_FOUND'}); const current=await store.getTargetConnection(target.id); const secretRef=parsed.data.secretRef??current?.secretRef??`schemaops-target-${target.id.slice(0,8)}`; let credentialVersion=current?.credentialVersion;
    if(parsed.data.secretBackend==='kubernetes') { if(!secretManager) return reply.code(503).send({code:'SECRET_MANAGER_NOT_CONFIGURED'}); const existing=parsed.data.password?undefined:await secretManager.read(secretRef); if(!parsed.data.password&&!existing) return reply.code(400).send({code:'PASSWORD_REQUIRED_FOR_NEW_SECRET'}); credentialVersion=(await secretManager.write(secretRef,connectionSecretFor(project.databaseEngine,{...parsed.data,password:parsed.data.password??existing?.password??''}))).version; } else if(parsed.data.password) return reply.code(400).send({code:'SECRET_BACKEND_WRITE_NOT_CONFIGURED'});
    const connection=await store.updateTargetConnection({targetId:target.id,host:parsed.data.host,port:parsed.data.port,databaseName:parsed.data.databaseName,schemaName:parsed.data.schemaName,username:parsed.data.username,secretBackend:parsed.data.secretBackend,secretRef,sslMode:parsed.data.sslMode,timeoutSeconds:parsed.data.timeoutSeconds,credentialVersion,updatedBy:actor.id}); if(!connection) return reply.code(404).send({code:'TARGET_NOT_FOUND'}); await store.recordTargetAudit({targetId:target.id,actorId:actor.id,action:'connection.settings_updated',resourceType:'target_connection',resourceId:target.id,metadata:{secretBackend:connection.secretBackend,secretRef:connection.secretRef,credentialVersion:connection.credentialVersion,correlationId:request.id}}); return connection;
  });
  app.post('/api/v1/targets/:targetId/connection/test', async (request, reply) => {
    const actor=actorFor(request); requirePermission(actor,'connection:test'); const targetId=uuid.safeParse(params(request).targetId); if(!targetId.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); const connection=await store.getTargetConnection(targetId.data); if(!connection) return reply.code(404).send({code:'TARGET_NOT_FOUND'}); const started=Date.now(); let result:{status:string;durationMs:number;error?:string}; try { if(!secretManager) throw new Error('SECRET_MANAGER_NOT_CONFIGURED'); const secret=await secretManager.read(connection.secretRef); if(!secret) throw new Error('CREDENTIAL_NOT_FOUND'); const tested=await connectionTester(connection.engine,{host:secret.host,port:secret.port,database:secret.database,user:secret.username,password:secret.password,schema:secret.schema,ssl:secret.sslMode!=='disable'}); result={status:'HEALTHY',durationMs:tested.durationMs}; } catch(error) { const message=error instanceof Error?error.message:'CONNECTION_TEST_FAILED'; result={status:message.includes('CREDENTIAL')?'AUTHENTICATION_FAILED':'FAILED',durationMs:Date.now()-started,error:message}; } const saved=await store.recordConnectionTest(targetId.data,{status:result.status as never,durationMs:result.durationMs,error:result.error,testedAt:new Date().toISOString()}); await store.recordTargetAudit({targetId:targetId.data,actorId:actor.id,action:'connection.tested',resourceType:'target_connection',resourceId:targetId.data,metadata:{status:result.status,durationMs:result.durationMs,error:result.error,correlationId:request.id}}); return {targetId:targetId.data,status:result.status,durationMs:result.durationMs,correlationId:request.id,error:result.error,connection:saved};
  });
  app.post('/api/v1/targets/:targetId/connection/rotate', async (request, reply) => {
    const actor=actorFor(request); requirePermission(actor,'access:admin'); const targetId=uuid.safeParse(params(request).targetId); const parsed=rotateCredentialSchema.safeParse(request.body); if(!targetId.success||!parsed.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); const target=await store.getTarget(targetId.data); const connection=await store.getTargetConnection(targetId.data); if(!target||!connection) return reply.code(404).send({code:'TARGET_NOT_FOUND'}); if(connection.secretBackend!=='kubernetes'||!secretManager) return reply.code(400).send({code:'SECRET_BACKEND_WRITE_NOT_CONFIGURED'}); const existing=await secretManager.read(connection.secretRef); if(!existing) return reply.code(409).send({code:'CREDENTIAL_NOT_FOUND'}); const version=(await secretManager.write(connection.secretRef,{...existing,password:parsed.data.password})).version; const updated=await store.updateTargetConnection({targetId:target.id,host:connection.host,port:connection.port,databaseName:connection.databaseName,schemaName:connection.schemaName,username:connection.username,secretBackend:connection.secretBackend,secretRef:connection.secretRef,sslMode:connection.sslMode,timeoutSeconds:connection.timeoutSeconds,credentialVersion:version,updatedBy:actor.id}); await store.recordTargetAudit({targetId:target.id,actorId:actor.id,action:'connection.credential_rotated',resourceType:'target_connection',resourceId:target.id,metadata:{secretRef:connection.secretRef,credentialVersion:version,reason:parsed.data.reason,correlationId:request.id}}); return {targetId:target.id,secretRef:connection.secretRef,credentialVersion:updated?.credentialVersion,correlationId:request.id};
  });
  app.get('/api/v1/targets/:targetId/connection/audit', async (request, reply) => { const targetId=uuid.safeParse(params(request).targetId); if(!targetId.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); requirePermission(actorFor(request),'target:view'); const events=await store.listAuditEvents(undefined,100); return {items:events.filter((event)=>event.resourceId===targetId.data&&event.resourceType==='target_connection')}; });
  app.get('/api/v1/targets/:targetId/ledger', async (request, reply) => { const targetId=uuid.safeParse(params(request).targetId); if(!targetId.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); requirePermission(actorFor(request),'target:view'); return {items:await store.listLedger(targetId.data)}; });
  app.get('/api/v1/targets/:targetId/drift', async (request, reply) => { const targetId=uuid.safeParse(params(request).targetId); if(!targetId.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); requirePermission(actorFor(request),'target:view'); const items=await store.listInventory(targetId.data); return {status:items.some((item)=>['CHANGED','FAILED'].includes(item.status))?'DRIFTED':'IN_SYNC',items:items.filter((item)=>['CHANGED','FAILED'].includes(item.status))}; });
  app.get('/api/v1/targets/:targetId/backup-plans', async (request, reply) => { const targetId=uuid.safeParse(params(request).targetId); if(!targetId.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); requirePermission(actorFor(request),'target:view'); return {item:await store.getBackupPlan(targetId.data)}; });
  app.post('/api/v1/targets/:targetId/backup-plans', async (request, reply) => { const actor=actorFor(request); requirePermission(actor,'access:admin'); const targetId=uuid.safeParse(params(request).targetId); const parsed=backupPlanSchema.safeParse(request.body); if(!targetId.success||!parsed.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); const target=await store.getTarget(targetId.data); if(!target) return reply.code(404).send({code:'TARGET_NOT_FOUND'}); const plan=await store.upsertBackupPlan({targetId:target.id,...parsed.data}); await store.recordTargetAudit({targetId:target.id,actorId:actor.id,action:'backup_plan.updated',resourceType:'backup_plan',resourceId:plan.id,metadata:{requiredBeforeExecute:plan.requiredBeforeExecute,retentionDays:plan.retentionDays}}); return reply.code(201).send(plan); });
  app.get('/api/v1/targets/:targetId/backup-artifacts', async (request, reply) => { const targetId=uuid.safeParse(params(request).targetId); if(!targetId.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); requirePermission(actorFor(request),'target:view'); return {items:await store.listBackupArtifacts(targetId.data)}; });
  app.post('/api/v1/targets/:targetId/backup-artifacts', async (request, reply) => { const actor=actorFor(request); requirePermission(actor,'access:admin'); const targetId=uuid.safeParse(params(request).targetId); const parsed=backupArtifactSchema.safeParse(request.body); if(!targetId.success||!parsed.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); const target=await store.getTarget(targetId.data); if(!target) return reply.code(404).send({code:'TARGET_NOT_FOUND'}); const artifact=await store.createBackupArtifact({targetId:target.id,...parsed.data,status:'SUCCEEDED'}); await store.recordTargetAudit({targetId:target.id,actorId:actor.id,action:'backup_artifact.recorded',resourceType:'backup_artifact',resourceId:artifact.id,metadata:{artifactRef:artifact.artifactRef,checksum:artifact.checksum,scopeFromVersion:artifact.scopeFromVersion,scopeToVersion:artifact.scopeToVersion,status:artifact.status}}); return reply.code(201).send(artifact); });
  app.post('/api/v1/targets/:targetId/backup', async (request, reply) => { const actor=actorFor(request); requirePermission(actor,'migration:execute'); const targetId=uuid.safeParse(params(request).targetId); if(!targetId.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); const target=await store.getTarget(targetId.data); if(!target) return reply.code(404).send({code:'TARGET_NOT_FOUND'}); const operation=await store.createOperation({targetId:target.id,type:'BACKUP',status:'QUEUED',actorId:actor.id,correlationId:request.id}); const artifact=await store.createBackupArtifact({targetId:target.id,operationId:operation.id,status:'REQUESTED'}); await store.appendExecutionLog({operationId:operation.id,sequence:1,stream:'system',message:'Backup request queued; artifact reference will be persisted by backup worker.',redacted:true,createdAt:new Date().toISOString()}); await store.recordTargetAudit({targetId:target.id,actorId:actor.id,action:'backup.requested',resourceType:'backup_artifact',resourceId:artifact.id,metadata:{operationId:operation.id}}); return reply.code(202).send({operationId:operation.id,artifactId:artifact.id,status:operation.status}); });
  app.get('/api/v1/targets/:targetId/native-history', async (request, reply) => { const targetId=uuid.safeParse(params(request).targetId); if(!targetId.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); requirePermission(actorFor(request),'target:view'); return {items:await store.listNativeHistoryImports(targetId.data)}; });
  app.post('/api/v1/targets/:targetId/native-history/import', async (request, reply) => { const actor=actorFor(request); requirePermission(actor,'target:sync'); const targetId=uuid.safeParse(params(request).targetId); const parsed=nativeHistorySchema.safeParse(request.body); if(!targetId.success||!parsed.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); const target=await store.getTarget(targetId.data); if(!target) return reply.code(404).send({code:'TARGET_NOT_FOUND'}); const record=await store.createNativeHistoryImport({targetId:target.id,...parsed.data}); await store.recordTargetAudit({targetId:target.id,actorId:actor.id,action:'native_history.imported',resourceType:'native_history_import',resourceId:record.id,metadata:{engine:record.engine,tableName:record.tableName,success:record.success}}); return reply.code(201).send(record); });

  app.post('/api/v1/targets/:targetId/plans', async (request, reply) => { const actor=actorFor(request); requirePermission(actor,'migration:plan'); const targetId=uuid.safeParse(params(request).targetId); const parsed=planSchema.safeParse(request.body ?? {}); if(!targetId.success||!parsed.success) return reply.code(400).send({code:'VALIDATION_ERROR',details:parsed.success?'invalid targetId':parsed.error.flatten()}); const target=await store.getTarget(targetId.data); if(!target) return reply.code(404).send({code:'TARGET_NOT_FOUND'}); return reply.code(201).send(await buildPlan(store,target.id,actor.id,parsed.data)); });
  app.get('/api/v1/targets/:targetId/plans', async (request, reply) => { const targetId=uuid.safeParse(params(request).targetId); if(!targetId.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); requirePermission(actorFor(request),'target:view'); return {items:await store.listPlans(targetId.data)}; });
  app.get('/api/v1/plans/:planId', async (request, reply) => { const planId=uuid.safeParse(params(request).planId); if(!planId.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); requirePermission(actorFor(request),'target:view'); const plan=await store.getPlan(planId.data); return plan?plan:reply.code(404).send({code:'PLAN_NOT_FOUND'}); });
  app.post('/api/v1/plans/:planId/approval', async (request, reply) => { const actor=actorFor(request); requirePermission(actor,'migration:execute'); const planId=uuid.safeParse(params(request).planId); const parsed=approvalSchema.safeParse(request.body); if(!planId.success||!parsed.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); const plan=await store.approvePlan(planId.data,actor.id,parsed.data.decision,parsed.data.reason); if(!plan) return reply.code(404).send({code:'PLAN_NOT_FOUND'}); await store.recordTargetAudit({targetId:plan.targetId,actorId:actor.id,action:`migration_plan.${parsed.data.decision.toLowerCase()}`,resourceType:'migration_plan',resourceId:plan.id,metadata:{reason:parsed.data.reason}}); return plan; });
  app.post('/api/v1/plans/:planId/preflight', async (request, reply) => { const actor=actorFor(request); requirePermission(actor,'migration:plan'); const planId=uuid.safeParse(params(request).planId); if(!planId.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); const plan=await store.getPlan(planId.data); if(!plan) return reply.code(404).send({code:'PLAN_NOT_FOUND'}); const result=await evaluatePreflight(store,plan); await store.recordTargetAudit({targetId:plan.targetId,actorId:actor.id,action:'migration_plan.preflight',resourceType:'migration_plan',resourceId:plan.id,metadata:result}); return {planId:plan.id,...result}; });

  app.post('/api/v1/plans/:planId/execute', async (request, reply) => { const actor=actorFor(request); requirePermission(actor,'migration:execute'); const planId=uuid.safeParse(params(request).planId); if(!planId.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); const plan=await store.getPlan(planId.data); if(!plan) return reply.code(404).send({code:'PLAN_NOT_FOUND'}); if(plan.status!=='APPROVED') return reply.code(409).send({code:'PLAN_NOT_APPROVED',status:plan.status}); const preflight=await evaluatePreflight(store,plan); if(!preflight.passed) return reply.code(409).send({code:'PREFLIGHT_REQUIRED',checks:preflight.checks}); const operation=await store.createOperation({targetId:plan.targetId,planId:plan.id,type:'EXECUTE',status:'QUEUED',actorId:actor.id,correlationId:request.id}); await store.appendExecutionLog({operationId:operation.id,sequence:1,stream:'system',message:'Operation queued after successful preflight.',redacted:true,createdAt:new Date().toISOString()}); await store.recordTargetAudit({targetId:plan.targetId,actorId:actor.id,action:'migration_operation.queued',resourceType:'operation',resourceId:operation.id,metadata:{planId:plan.id,itemCount:plan.items.length}}); if(process.env.SCHEMAOPS_OPERATION_WORKER_ENABLED==='true') void executeOperation(store,operation.id); return reply.code(202).send({operationId:operation.id,status:operation.status}); });
  app.get('/api/v1/targets/:targetId/operations', async (request, reply) => { const targetId=uuid.safeParse(params(request).targetId); if(!targetId.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); requirePermission(actorFor(request),'target:view'); return {items:await store.listOperations(targetId.data)}; });
  app.get('/api/v1/operations/:operationId', async (request, reply) => { const operationId=uuid.safeParse(params(request).operationId); if(!operationId.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); requirePermission(actorFor(request),'target:view'); const operations=await store.listOperations(); const operation=operations.find((item)=>item.id===operationId.data); if(!operation) return reply.code(404).send({code:'OPERATION_NOT_FOUND'}); return {...operation,logs:await store.listExecutionLogs(operation.id)}; });
  app.get('/api/v1/audit-events', async (request) => { requirePermission(actorFor(request),'target:view'); return {items:await store.listAuditEvents(undefined,100)}; });
  app.post('/api/v1/operations/:operationId/rollback/undo', async (request, reply) => { const actor=actorFor(request); requirePermission(actor,'migration:rollback'); const operationId=uuid.safeParse(params(request).operationId); if(!operationId.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); const source=(await store.listOperations()).find((item)=>item.id===operationId.data); if(!source) return reply.code(404).send({code:'OPERATION_NOT_FOUND'}); if(source.type!=='EXECUTE'||source.status!=='SUCCEEDED'||!source.planId) return reply.code(409).send({code:'UNDO_SOURCE_NOT_ROLLBACKABLE'}); const operation=await store.createOperation({targetId:source.targetId,type:'UNDO',status:'QUEUED',actorId:actor.id,correlationId:request.id,sourceOperationId:source.id}); await store.appendExecutionLog({operationId:operation.id,sequence:1,stream:'system',message:'Undo rollback queued as a separate operation; original ledger remains immutable.',redacted:true,createdAt:new Date().toISOString()}); await store.recordTargetAudit({targetId:source.targetId,actorId:actor.id,action:'rollback.undo.requested',resourceType:'operation',resourceId:operation.id,metadata:{sourceOperationId:source.id}}); if(process.env.SCHEMAOPS_OPERATION_WORKER_ENABLED==='true') void executeOperation(store,operation.id); return reply.code(202).send({operationId:operation.id,status:operation.status}); });
  app.post('/api/v1/targets/:targetId/rollback/restore', async (request, reply) => { const actor=actorFor(request); requirePermission(actor,'migration:rollback'); const targetId=uuid.safeParse(params(request).targetId); const parsed=z.object({artifactId:uuid}).safeParse(request.body); if(!targetId.success||!parsed.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); const artifacts=await store.listBackupArtifacts(targetId.data); const artifact=artifacts.find((item)=>item.id===parsed.data.artifactId&&item.status==='SUCCEEDED'); if(!artifact) return reply.code(409).send({code:'BACKUP_ARTIFACT_NOT_READY'}); const operation=await store.createOperation({targetId:targetId.data,type:'RESTORE',status:'QUEUED',actorId:actor.id,correlationId:request.id}); await store.appendExecutionLog({operationId:operation.id,sequence:1,stream:'system',message:`Restore queued from backup artifact ${artifact.id}.`,redacted:true,createdAt:new Date().toISOString()}); await store.recordTargetAudit({targetId:targetId.data,actorId:actor.id,action:'rollback.restore.requested',resourceType:'operation',resourceId:operation.id,metadata:{artifactId:artifact.id}}); return reply.code(202).send({operationId:operation.id,status:operation.status}); });

  app.post('/api/v1/targets/:targetId/manual-migrations', async (request, reply) => { const actor=actorFor(request); requirePermission(actor,'migration:plan'); const targetId=uuid.safeParse(params(request).targetId); const parsed=manualMigrationSchema.safeParse(request.body); if(!targetId.success||!parsed.success) return reply.code(400).send({code:'VALIDATION_ERROR',details:parsed.success?'invalid targetId':parsed.error.flatten()}); const target=await store.getTarget(targetId.data); if(!target) return reply.code(404).send({code:'TARGET_NOT_FOUND'}); const migration=await store.createManualMigration({targetId:target.id,sourceType:'MANUAL_UI',sqlPayload:parsed.data.sqlPayload,checksum:checksumSql(parsed.data.sqlPayload),versionContext:parsed.data.versionContext,executionLabel:parsed.data.executionLabel,executionSequence:parsed.data.executionSequence,outOfOrder:parsed.data.outOfOrder,reason:parsed.data.reason,actorId:actor.id,status:'DRAFT'}); const {sqlPayload:_sqlPayload,...metadata}=migration; await store.recordTargetAudit({targetId:target.id,actorId:migration.actorId,action:'manual_migration.created',resourceType:'manual_migration',resourceId:migration.id,metadata:{sourceType:migration.sourceType,checksum:migration.checksum,versionContext:migration.versionContext,executionSequence:migration.executionSequence,outOfOrder:migration.outOfOrder,status:migration.status}}); return reply.code(201).send(metadata); });
  app.get('/api/v1/targets/:targetId/manual-migrations', async (request, reply) => { const targetId=uuid.safeParse(params(request).targetId); if(!targetId.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); requirePermission(actorFor(request),'target:view'); const target=await store.getTarget(targetId.data); if(!target) return reply.code(404).send({code:'TARGET_NOT_FOUND'}); const migrations=await store.listManualMigrations(target.id); return {items:migrations.map(({sqlPayload:_sqlPayload,...metadata})=>metadata)}; });
  app.post('/api/v1/manual-migrations/:manualMigrationId/plan', async (request, reply) => { const actor=actorFor(request); requirePermission(actor,'migration:plan'); const manualId=uuid.safeParse(params(request).manualMigrationId); if(!manualId.success) return reply.code(400).send({code:'VALIDATION_ERROR'}); const migration=await store.getManualMigration(manualId.data); if(!migration) return reply.code(404).send({code:'MANUAL_MIGRATION_NOT_FOUND'}); if(migration.status!=='DRAFT') return reply.code(409).send({code:'MANUAL_MIGRATION_NOT_DRAFT',status:migration.status}); const item={sourceType:'MANUAL_UI' as const,manualMigrationId:migration.id,path:`MANUAL_UI:${migration.id}`,kind:'MANUAL',version:migration.versionContext,checksum:migration.checksum,executionSequence:migration.executionSequence ?? 1,outOfOrder:migration.outOfOrder,status:'PENDING' as const}; const plan=await store.createPlan({targetId:migration.targetId,status:'APPROVAL_REQUIRED',fingerprint:checksumSql(`${item.path}:${item.checksum}:${item.executionSequence}`),autoApprove:false,createdBy:actor.id,items:[item]}); await store.recordTargetAudit({targetId:migration.targetId,actorId:actor.id,action:'manual_migration.planned',resourceType:'migration_plan',resourceId:plan.id,metadata:{manualMigrationId:migration.id}}); return reply.code(201).send(plan); });
  return app;
}
