'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import AppShell from '../../components/AppShell';
import LoadingState from '../../components/LoadingState';
import StatusBadge from '../../components/StatusBadge';
import { api, type Target } from '../../../lib/api';

export default function TargetPage() { const {targetId}=useParams<{targetId:string}>(); const [target,setTarget]=useState<Target>(); const [message,setMessage]=useState(''); useEffect(()=>{api<{items:Target[]}>('/targets').then((r)=>setTarget(r.items.find((item)=>item.id===targetId))).catch((e)=>setMessage(e instanceof Error?e.message:'TARGET_FAILED'));},[targetId]); return <AppShell breadcrumb={`Tenant / Project / Environment / ${target?.name??targetId}`}><div className="page-heading"><div><p className="eyebrow">TARGET CONTROL</p><h1>{target?.name??'Database target'}</h1><p className="muted">{target?.databaseName} · {target?.schemaName} · ref {target?.gitRef}</p></div><StatusBadge status="HEALTHY" /></div>{!target&&!message?<LoadingState/>:null}{message?<div className="alert danger-box">{message}</div>:null}{target?<><div className="alert warning-box"><strong>Production guard:</strong> target execution remains API-gated. Connection credentials are referenced through <span className="code">{target.secretRef}</span>; plaintext secrets are never returned to this UI.</div><section className="detail-grid"><article className="panel"><p className="label-caps">CONNECTION HEALTH</p><h2>Target configuration</h2><dl className="definition-list"><dt>Engine</dt><dd>Resolved from project</dd><dt>Database</dt><dd className="code">{target.databaseName}</dd><dt>Schema</dt><dd className="code">{target.schemaName}</dd><dt>Git ref</dt><dd className="code">{target.gitRef}</dd><dt>Secret reference</dt><dd className="code">{target.secretRef}</dd></dl></article><article className="panel"><p className="label-caps">OPERATIONS</p><h2>Migration lifecycle</h2><div className="action-stack"><Link className="button primary" href={`/targets/${target.id}/migrations`}>Open migration inventory</Link><Link className="button secondary" href={`/targets/${target.id}/plans`}>Review plans</Link><Link className="button secondary" href={`/targets/${target.id}/operations`}>Execution history</Link></div></article></section></>:null}</AppShell>; }
