'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import AppShell from '../../components/AppShell';
import LoadingState from '../../components/LoadingState';
import StatusBadge from '../../components/StatusBadge';
import { api, type Target, type TargetConnection } from '../../../lib/api';

export default function TargetPage() {
  const { targetId } = useParams<{ targetId: string }>();
  const [target, setTarget] = useState<Target>(); const [connection, setConnection] = useState<TargetConnection>(); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false);
  async function load() { const [targets, value] = await Promise.all([api<{ items: Target[] }>('/targets'), api<TargetConnection>(`/targets/${targetId}/connection`)]); setTarget(targets.items.find((item) => item.id === targetId)); setConnection(value); }
  useEffect(() => { load().catch((e) => setMessage(e instanceof Error ? e.message : 'TARGET_FAILED')); }, [targetId]);
  async function sync() { if (!target) return; setBusy(true); setMessage('Syncing the target Git ref…'); try { const result = await api<{ status: string; commitSha?: string }>(`/projects/${target.projectId}/sync`, { method: 'POST', body: JSON.stringify({ gitRef: target.gitRef }) }); setMessage(`Source sync ${result.status.toLowerCase()}${result.commitSha ? ` at ${result.commitSha.slice(0, 12)}` : ''}.`); } catch (e) { setMessage(e instanceof Error ? e.message : 'GIT_SYNC_FAILED'); } finally { setBusy(false); } }
  return <AppShell breadcrumb={`Tenant / Project / Environment / ${target?.name ?? targetId}`}><div className="page-heading"><div><p className="eyebrow">TARGET CONTROL</p><h1>{target?.name ?? 'Database target'}</h1><p className="muted">{target?.databaseName} · {target?.schemaName} · ref {target?.gitRef}</p></div><div className="button-row"><button className="button secondary" disabled={busy || !target} type="button" onClick={sync}>Sync target ref</button><StatusBadge status={connection?.lastTestStatus ?? 'NOT_TESTED'} /></div></div>{!target && !message ? <LoadingState /> : null}{message ? <div className="alert info-box" role="status">{message}</div> : null}{target ? <><div className="alert warning-box"><strong>Production guard:</strong> target execution remains API-gated. Connection credentials are referenced through <span className="code">{target.secretRef}</span>; plaintext secrets are never returned to this UI.</div><section className="detail-grid"><article className="panel"><p className="label-caps">CONNECTION HEALTH</p><h2>Target configuration</h2><dl className="definition-list"><dt>Engine</dt><dd>Resolved from project</dd><dt>Database</dt><dd className="code">{target.databaseName}</dd><dt>Schema</dt><dd className="code">{target.schemaName}</dd><dt>Git ref</dt><dd className="code">{target.gitRef}</dd><dt>Secret reference</dt><dd className="code">{target.secretRef}</dd></dl></article><article className="panel"><p className="label-caps">OPERATIONS</p><h2>Migration lifecycle</h2><div className="action-stack"><Link className="button primary" href={`/targets/${target.id}/connection`}>Connection settings</Link><Link className="button secondary" href={`/targets/${target.id}/migrations`}>Open migration inventory</Link><Link className="button secondary" href={`/targets/${target.id}/plans`}>Review plans</Link><Link className="button secondary" href={`/targets/${target.id}/operations`}>Execution history</Link><Link className="button secondary" href={`/targets/${target.id}/connection/audit`}>Connection audit</Link></div></article></section></> : null}</AppShell>;
}
