'use client';

import Link from 'next/link';
import { useParams } from 'next/navigation';
import { useEffect, useState } from 'react';
import AppShell from '../../../components/AppShell';
import LoadingState from '../../../components/LoadingState';
import StatusBadge from '../../../components/StatusBadge';
import { api, type InventoryItem } from '../../../../lib/api';

export default function InventoryPage() { const {targetId}=useParams<{targetId:string}>(); const [items,setItems]=useState<InventoryItem[]>(); const [message,setMessage]=useState(''); useEffect(()=>{api<{items:InventoryItem[]}>(`/targets/${targetId}/inventory`).then((r)=>setItems(r.items)).catch((e)=>setMessage(e instanceof Error?e.message:'INVENTORY_FAILED'));},[targetId]); async function createPlan(){try{const plan=await api<{id:string}>(`/targets/${targetId}/plans`,{method:'POST',body:JSON.stringify({})});window.location.assign(`/plans/${plan.id}`);}catch(e){setMessage(e instanceof Error?e.message:'PLAN_FAILED');}} return <AppShell breadcrumb={`Tenant / Target / ${targetId} / Migration inventory`}><div className="page-heading"><div><p className="eyebrow">MIGRATION INVENTORY</p><h1>Source and target state</h1><p className="muted">Parsed V/R/U files are compared with the immutable target ledger.</p></div><div className="button-row"><button className="button secondary" type="button" onClick={()=>window.location.reload()}>Refresh</button><button className="button primary" type="button" onClick={createPlan}>Create plan</button></div></div>{message?<div className="alert danger-box">{message}</div>:null}{!items&&!message?<LoadingState/>:null}<section className="panel table-panel">{items?.length?<table><thead><tr><th>Status</th><th>Migration</th><th>Kind</th><th>Checksum</th><th>Applied at</th><th>Sequence</th></tr></thead><tbody>{items.map((item)=><tr key={item.path}><td><StatusBadge status={item.status}/></td><td><strong>{item.description}</strong><br/><span className="small code">{item.path}</span></td><td className="code">{item.kind}</td><td className="code checksum">{item.checksum.slice(0,16)}…</td><td className="small">{item.appliedAt?new Date(item.appliedAt).toLocaleString():'—'}</td><td>{item.executionSequence??'—'} {item.outOfOrder?<span className="small warning-text">OOO</span>:null}</td></tr>)}</tbody></table>:<div className="empty-state"><h2>No source snapshot</h2><p className="muted">Sync the project repository before creating a plan.</p><Link className="text-link" href="/projects">Go to projects →</Link></div>}</section></AppShell>; }
