'use client';

import Link from 'next/link';
import { type FormEvent, useEffect, useState } from 'react';
import AppShell from '../components/AppShell';
import LoadingState from '../components/LoadingState';
import { api, type Project, type Tenant } from '../../lib/api';

type ProjectForm = { tenantId: string; name: string; databaseEngine: string; repositoryUrl: string; defaultRef: string; migrationPath: string };
const emptyForm: ProjectForm = { tenantId: '', name: '', databaseEngine: 'postgresql', repositoryUrl: '', defaultRef: 'master', migrationPath: 'migrations' };

export default function ProjectsPage() {
  const [projects, setProjects] = useState<Project[]>();
  const [tenants, setTenants] = useState<Tenant[]>();
  const [message, setMessage] = useState('');
  const [form, setForm] = useState<ProjectForm>(emptyForm);
  const [showForm, setShowForm] = useState(false);
  const [busy, setBusy] = useState(false);
  useEffect(() => { Promise.all([api<{ items: Project[] }>('/projects'), api<{ items: Tenant[] }>('/tenants')]).then(([projectResponse, tenantResponse]) => { setProjects(projectResponse.items); setTenants(tenantResponse.items); setForm((current) => ({ ...current, tenantId: current.tenantId || tenantResponse.items[0]?.id || '' })); }).catch((error) => setMessage(error instanceof Error ? error.message : 'PROJECTS_FAILED')); }, []);
  function change(name: keyof ProjectForm, value: string) { setForm((current) => ({ ...current, [name]: value })); }
  async function createProject(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setMessage(''); try { const project = await api<Project>('/projects', { method: 'POST', body: JSON.stringify(form) }); setProjects((current) => [project, ...(current ?? [])]); setForm({ ...emptyForm, tenantId: form.tenantId }); setShowForm(false); setMessage(`Project “${project.name}” created. Open it to sync the repository.`); } catch (error) { setMessage(error instanceof Error ? error.message : 'PROJECT_CREATE_FAILED'); } finally { setBusy(false); } }
  return <AppShell breadcrumb="Tenant / Projects"><div className="page-heading"><div><p className="eyebrow">PROJECTS</p><h1>Migration repositories</h1><p className="muted">Each project fixes one target database engine and can map to multiple environments.</p></div><button className="button primary" type="button" onClick={() => { setMessage(''); setShowForm(true); }}>New project</button></div>{message ? <div className="alert info-box" role="status">{message}</div> : null}{showForm ? <ProjectOnboarding form={form} tenants={tenants ?? []} busy={busy} change={change} close={() => setShowForm(false)} submit={createProject} refreshTenants={(tenant) => { setTenants((current) => [...(current ?? []), tenant]); change('tenantId', tenant.id); }} /> : null}{!projects && !message ? <LoadingState /> : null}<section className="panel">{projects?.length ? <table><thead><tr><th>Project</th><th>Engine</th><th>Repository</th><th>Default ref</th><th>Migration path</th></tr></thead><tbody>{projects.map((project) => <tr key={project.id}><td><Link className="text-link" href={`/projects/${project.id}`}>{project.name}</Link><br /><span className="small muted">{project.id}</span></td><td><span className="code">{project.databaseEngine}</span></td><td className="truncate">{project.repositoryUrl}</td><td className="code">{project.defaultRef}</td><td className="code">{project.migrationPath}</td></tr>)}</tbody></table> : <div className="empty-state"><h2>No projects yet</h2><p className="muted">Start the onboarding flow to register a repository and database engine.</p><button className="button primary" type="button" onClick={() => setShowForm(true)}>Create your first project</button></div>}</section></AppShell>;
}

function ProjectOnboarding({ form, tenants, busy, change, close, submit, refreshTenants }: { form: ProjectForm; tenants: Tenant[]; busy: boolean; change: (name: keyof ProjectForm, value: string) => void; close: () => void; submit: (event: FormEvent<HTMLFormElement>) => Promise<void>; refreshTenants: (tenant: Tenant) => void }) {
  const [tenantName, setTenantName] = useState(''); const [tenantSlug, setTenantSlug] = useState(''); const [tenantBusy, setTenantBusy] = useState(false); const [tenantError, setTenantError] = useState('');
  async function createTenant() { setTenantBusy(true); setTenantError(''); try { const tenant = await api<Tenant>('/tenants', { method: 'POST', body: JSON.stringify({ name: tenantName, slug: tenantSlug }) }); refreshTenants(tenant); setTenantName(''); setTenantSlug(''); } catch (error) { setTenantError(error instanceof Error ? error.message : 'TENANT_CREATE_FAILED'); } finally { setTenantBusy(false); } }
  return <section className="panel onboarding-panel"><div className="section-heading"><div><p className="eyebrow">PROJECT ONBOARDING · STEP 1</p><h2>Register a migration repository</h2><p className="muted">The project engine is fixed at creation and is never translated between database vendors.</p></div><button className="icon-button" type="button" onClick={close} aria-label="Close onboarding">×</button></div>{!tenants.length ? <div className="alert warning-box"><strong>Create a tenant first.</strong><div className="form-grid compact-form"><label>Tenant name<input value={tenantName} onChange={(event) => setTenantName(event.target.value)} placeholder="Demo Tenant" /></label><label>Tenant slug<input value={tenantSlug} onChange={(event) => setTenantSlug(event.target.value)} placeholder="demo-tenant" /></label></div><button className="button secondary" type="button" disabled={tenantBusy || !tenantName || !tenantSlug} onClick={createTenant}>{tenantBusy ? 'Creating…' : 'Create tenant'}</button>{tenantError ? <p className="small danger-text">{tenantError}</p> : null}</div> : null}<form className="form" onSubmit={submit}><div className="form-grid"><label>Tenant<select required value={form.tenantId} onChange={(event) => change('tenantId', event.target.value)}><option value="">Select tenant</option>{tenants.map((tenant) => <option value={tenant.id} key={tenant.id}>{tenant.name} ({tenant.slug})</option>)}</select></label><label>Project name<input required maxLength={120} value={form.name} placeholder="database-demo" onChange={(event) => change('name', event.target.value)} /></label><label>Database engine<select value={form.databaseEngine} onChange={(event) => change('databaseEngine', event.target.value)}><option value="postgresql">PostgreSQL</option><option value="mysql">MySQL</option><option value="oracle">Oracle</option><option value="sqlserver">SQL Server</option></select></label><label>Repository URL<input required type="url" value={form.repositoryUrl} placeholder="https://github.com/org/repository.git" onChange={(event) => change('repositoryUrl', event.target.value)} /><span className="small muted">Repository credentials are never accepted in the URL.</span></label><label>Default Git ref<input required value={form.defaultRef} placeholder="master" onChange={(event) => change('defaultRef', event.target.value)} /></label><label>Migration path<input required value={form.migrationPath} placeholder="migrations" onChange={(event) => change('migrationPath', event.target.value)} /></label></div><div className="button-row"><button className="button secondary" type="button" onClick={close}>Cancel</button><button className="button primary" disabled={busy || !tenants.length} type="submit">{busy ? 'Creating…' : 'Create project'}</button></div></form></section>;
}
